  /* ---------- Config ---------- */
export const WA_NUMBER = '918142161862';
export const MESSAGES = {
    general: 'Hi, I need a custom Diploma, mini or final-year project in ECE, EEE, CSE, IoT, Mechanical or Web Application development. Please share the process, price and delivery time.',
    custom: 'Hi, I have my own B.Tech project idea and would like a quote to build it.',
    project: (name) => `Hi, I would like to order the B.Tech project: ${name}. Please share the scope, price and estimated delivery time.`,
    category: (branch, cat) => `Hi, I am looking for a B.Tech ${branch} project in ${cat}. Can we discuss suitable ideas?`
  };
export const waLink = (text) => `https://wa.me/${WA_NUMBER}?text=${encodeURIComponent(text)}`;

  /* ---------- Icons (24x24 stroke paths) ---------- */
export const ICONS = {
    code: '<path d="m8 6-6 6 6 6m8-12 6 6-6 6M14 3l-4 18"/>',
    meter: '<path d="M12 14l4-4"/><path d="M3.3 19a10 10 0 1 1 17.4 0"/><circle cx="12" cy="14" r="1.5"/>',
    solar: '<rect x="3" y="10" width="18" height="10" rx="1"/><path d="M3 15h18M9 10v10M15 10v10M12 2v4M5 4l1.8 1.8M19 4l-1.8 1.8"/>',
    pf: '<path d="M2 12c2-6 4-6 6 0s4 6 6 0 4-6 6 0"/><path d="M2 12h20" opacity=".35"/>',
    transformer: '<path d="M9 3v18M15 3v18"/><path d="M3 6c3 0 3 3 6 3M3 11c3 0 3 3 6 3M3 16c3 0 3 3 6 3M21 6c-3 0-3 3-6 3M21 11c-3 0-3 3-6 3M21 16c-3 0-3 3-6 3"/>',
    light: '<path d="M9 18h6M10 22h4M12 2a7 7 0 0 0-4 12.7V16h8v-1.3A7 7 0 0 0 12 2z"/>',
    wireless: '<path d="M5 12.5a10 10 0 0 1 14 0M8.5 16a5 5 0 0 1 7 0M2 9a15 15 0 0 1 20 0"/><circle cx="12" cy="19.5" r="1"/>',
    load: '<path d="M4 21v-7M4 10V3M12 21v-9M12 8V3M20 21v-5M20 12V3M1 14h6M9 8h6M17 16h6"/>',
    battery: '<rect x="2" y="7" width="17" height="10" rx="2"/><path d="M22 11v2M6 10v4M10 10v4M14 10v4"/>',
    motor: '<rect x="3" y="6" width="13" height="12" rx="2"/><path d="M16 10h3v4h-3M19 12h3M6 6V4h7v2M7 10v4M10 10v4M13 10v4"/>',
    conveyor: '<circle cx="6" cy="17" r="3"/><circle cx="18" cy="17" r="3"/><path d="M6 14h12M6 20h12"/><rect x="7" y="6" width="5" height="5" rx="1"/><rect x="13.5" y="8" width="4" height="3" rx=".5"/>',
    press: '<path d="M4 3h16M12 3v5M7 8h10v3H7zM4 21h16M7 21v-4h10v4"/>',
    arm: '<path d="M4 21h8M8 21v-4"/><circle cx="8" cy="15" r="2"/><path d="M9.5 13.5 15 7"/><circle cx="16" cy="6" r="2"/><path d="M18 6h3M20.5 4v4"/>',
    pneumatic: '<rect x="2" y="8" width="12" height="8" rx="1"/><path d="M14 12h7M21 9v6M6 8V5M10 8V5"/>',
    lift: '<path d="M3 21h18M7 21V10M17 21V10M5 10h14"/><rect x="6" y="4" width="12" height="6" rx="1.5"/>',
    gear: '<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9 7 7M17 17l2.1 2.1M4.9 19.1 7 17M17 7l2.1-2.1"/>',
    shield: '<path d="M12 2 4 5v6c0 5 3.5 9.5 8 11 4.5-1.5 8-6 8-11V5z"/><path d="m9 12 2 2 4-4"/>',
    cnc: '<rect x="3" y="3" width="18" height="13" rx="1"/><path d="M3 7h18M12 7v5M10 12h4M7 21h10M12 16v5"/>',
    chip: '<rect x="5" y="5" width="14" height="14" rx="2"/><rect x="9" y="9" width="6" height="6"/><path d="M9 2v3M15 2v3M9 19v3M15 19v3M19 9h3M19 15h3M2 9h3M2 15h3"/>',
    bolt: '<path d="M13 2 4 14h7l-1 8 9-12h-7z"/>',
    plug: '<path d="M9 2v6M15 2v6M6 8h12v4a6 6 0 0 1-12 0zM12 18v4"/>',
    wave: '<path d="M2 12h3l3-7 4 14 3-7h7"/>',
    ruler: '<path d="M3 17 17 3l4 4L7 21z"/><path d="m7 13 2 2M10 10l2 2M13 7l2 2"/>',
    drop: '<path d="M12 2s7 7.5 7 12a7 7 0 0 1-14 0c0-4.5 7-12 7-12z"/>',
    box: '<path d="M21 8 12 3 3 8v8l9 5 9-5z"/><path d="M3 8l9 5 9-5M12 13v8"/>',
    factory: '<path d="M2 21V10l6 4V10l6 4V6l8 4v11z"/><path d="M6 17h2M11 17h2M16 17h2"/>'
  };

  /* ---------- Project data ---------- */
export const PROJECTS = [
    // ===== CSE =====
    {"title": "Campus Placement Portal", "branch": "CSE", "tags": ["Web Development"], "level": "Beginner", "demo": false, "icon": "code", "desc": "Manage placement drives, student profiles and job applications in one portal.", "overview": "Manage placement drives, student profiles and job applications in one portal.", "problem": "Placement information scattered across messages makes applications hard to track.", "solution": "Build a role-based portal for students and placement coordinators.", "components": ["Student dashboard", "Recruiter listings", "Application tracker"], "tech": ["React", "Node.js", "SQLite"], "functions": ["Student and coordinator login", "Search and apply for placement drives", "Track application status"]},
    {"title": "College FAQ Chatbot", "branch": "CSE", "tags": ["AI / ML"], "level": "Intermediate", "demo": false, "icon": "chip", "desc": "Answer common college questions using a searchable knowledge base.", "overview": "Answer common college questions using a searchable knowledge base.", "problem": "Students repeatedly search multiple pages for admission and campus information.", "solution": "Retrieve relevant answers from an approved college FAQ dataset and show source references.", "components": ["FAQ dataset", "Retrieval service", "Chat interface"], "tech": ["Python", "Flask", "scikit-learn"], "functions": ["Natural-language question input", "Answers with source references", "Fallback for unknown questions"]},
    {"title": "Student Performance Analytics", "branch": "CSE", "tags": ["Data Analytics"], "level": "Intermediate", "demo": false, "icon": "meter", "desc": "Explore academic trends with interactive dashboards and visual reports.", "overview": "Explore academic trends with interactive dashboards and visual reports.", "problem": "Raw mark sheets make it difficult to spot subject-level trends.", "solution": "Analyse anonymised sample records and visualise performance by subject and semester.", "components": ["Sample academic dataset", "Data processing pipeline", "Analytics dashboard"], "tech": ["Python", "Pandas", "Streamlit"], "functions": ["Import and validate CSV data", "Compare subject and semester trends", "Export summary reports"]},
    {"title": "Phishing URL Detection", "branch": "CSE", "tags": ["Cybersecurity"], "level": "Advanced", "demo": false, "icon": "shield", "desc": "Classify potentially suspicious URLs using machine learning and explainable features.", "overview": "Classify potentially suspicious URLs using machine learning and explainable features.", "problem": "Deceptive URLs can be difficult to distinguish from legitimate links.", "solution": "Train and evaluate a classifier on labelled URL data without visiting submitted links.", "components": ["Labelled URL dataset", "Feature extractor", "Prediction interface"], "tech": ["Python", "scikit-learn", "Flask"], "functions": ["Extract URL structure features", "Display a prediction with limitations", "Compare precision and recall on held-out data"]},
    {"title": "Smart Library Management System", "branch": "CSE", "tags": ["Web Development"], "level": "Beginner", "demo": false, "icon": "code", "desc": "Track books, borrowing and reservations with a searchable web application.", "overview": "Track books, borrowing and reservations with a searchable web application.", "problem": "Manual lending records lead to missed returns and unclear book availability.", "solution": "Create a library portal with book inventory and borrowing workflows.", "components": ["Book catalogue", "Member portal", "Lending database"], "tech": ["Django", "SQLite", "HTML / CSS"], "functions": ["Search book availability", "Issue and return books", "Manage reservations and due dates"]},
    {"title": "Helpdesk Ticket Management", "branch": "CSE", "tags": ["Automation"], "level": "Intermediate", "demo": false, "icon": "code", "desc": "Organise support requests, assignments and resolution updates.", "overview": "Organise support requests, assignments and resolution updates.", "problem": "Requests sent through separate channels are easily overlooked.", "solution": "Centralise requests in a role-based ticket system with status tracking.", "components": ["Ticket database", "Staff dashboard", "Request form"], "tech": ["React", "Express", "PostgreSQL"], "functions": ["Create and categorise tickets", "Assign tickets to staff", "Filter by priority and resolution status"]},
    // ===== EEE =====
    { title: 'IoT-Based Smart Energy Monitoring System', branch: 'EEE', tags: ['IoT'], level: 'Intermediate', demo: true, icon: 'meter',
      desc: 'Track voltage, current, power and units consumed in real time on a mobile or web dashboard.',
      overview: 'A connected energy meter that measures household or lab consumption and publishes live readings to the cloud.',
      problem: 'Conventional meters show consumption only at billing time, so users cannot see which loads waste energy or when usage spikes.',
      solution: 'An ESP32 reads a PZEM-004T energy module and sends data over Wi-Fi to a dashboard with alerts when usage crosses a set limit.',
      components: ['ESP32', 'PZEM-004T energy module', 'CT coil', 'Relay module', '16×2 LCD', '5 V power supply'],
      tech: ['Embedded C / Arduino IDE', 'Wi-Fi', 'Blynk / ThingSpeak', 'MQTT'],
      functions: ['Live voltage, current, power and kWh readings', 'Usage alert when a threshold is crossed', 'Remote load ON/OFF through relay', 'Daily consumption graph'] },
    { title: 'Solar Power Monitoring System', branch: 'EEE', tags: ['IoT'], level: 'Beginner', demo: true, icon: 'solar',
      desc: 'Monitor solar panel voltage, current, power and battery level from anywhere.',
      overview: 'A monitoring unit for small solar installations that logs generation and battery status to a cloud dashboard.',
      problem: 'Owners of small solar setups rarely know how much energy is generated or when panel performance drops due to dust or faults.',
      solution: 'Voltage and current sensors measure panel and battery values; a microcontroller uploads readings for trend analysis.',
      components: ['ESP32', 'INA219 current sensor', 'Voltage divider', 'Solar panel', 'Battery', 'OLED display'],
      tech: ['Arduino IDE', 'ThingSpeak', 'Wi-Fi'],
      functions: ['Panel voltage, current and power readings', 'Battery charge level indication', 'Daily generation logging', 'Low-generation alert'] },
    { title: 'Smart Automatic Power Factor Controller', branch: 'EEE', tags: ['Automation'], level: 'Intermediate', demo: false, icon: 'pf',
      desc: 'Measure power factor and switch capacitor banks automatically to bring it close to unity.',
      overview: 'An automatic power factor correction unit for inductive loads such as motors and fans.',
      problem: 'Low power factor from inductive loads increases line current, losses and electricity penalties for industries.',
      solution: 'Zero-crossing detection measures the phase shift between voltage and current, and relays switch capacitor stages as needed.',
      components: ['Arduino / PIC microcontroller', 'Potential transformer', 'Current transformer', 'Zero-crossing detectors', 'Capacitor bank', 'Relays', 'LCD'],
      tech: ['Embedded C', 'Power factor measurement', 'Proteus simulation'],
      functions: ['Real-time power factor display', 'Automatic capacitor switching', 'Before and after correction readings', 'Overcorrection protection'] },
    { title: 'IoT-Based Transformer Monitoring', branch: 'EEE', tags: ['IoT'], level: 'Intermediate', demo: true, icon: 'transformer',
      desc: 'Monitor oil temperature, load current and voltage of a distribution transformer remotely.',
      overview: 'A condition-monitoring system that warns before a transformer is overloaded or overheated.',
      problem: 'Distribution transformers often fail from overload or overheating because they are inspected only manually.',
      solution: 'Sensors measure temperature, current and voltage; the controller uploads data and sends alerts when limits are crossed.',
      components: ['ESP32', 'DS18B20 temperature sensor', 'ACS712 current sensor', 'ZMPT101B voltage sensor', 'Buzzer', 'LCD'],
      tech: ['Arduino IDE', 'IoT dashboard', 'SMS / app alerts'],
      functions: ['Live transformer parameters', 'Overload and over-temperature alerts', 'Historical trend charts', 'Local alarm and display'] },
    { title: 'Smart Street Light Automation', branch: 'EEE', tags: ['Automation', 'IoT'], level: 'Beginner', demo: true, icon: 'light',
      desc: 'Street lights that switch on at dusk and brighten only when vehicles or people pass.',
      overview: 'An energy-saving street lighting system using light and motion sensing.',
      problem: 'Street lights run at full brightness all night, wasting energy on empty roads.',
      solution: 'An LDR detects darkness and IR sensors detect movement; LEDs dim when idle and brighten when someone passes.',
      components: ['Arduino', 'LDR', 'IR sensors', 'High-power LEDs', 'MOSFET drivers', 'Power supply'],
      tech: ['Arduino IDE', 'PWM dimming', 'Optional IoT fault reporting'],
      functions: ['Automatic dusk-to-dawn operation', 'Motion-based brightness control', 'Energy saving compared to fixed lighting', 'Optional fault alert per pole'] },
    { title: 'Wireless Energy Monitoring System', branch: 'EEE', tags: ['IoT'], level: 'Intermediate', demo: false, icon: 'wireless',
      desc: 'Multiple meter nodes send readings wirelessly to one central monitoring station.',
      overview: 'A multi-point energy monitoring network for hostels, labs or small industries.',
      problem: 'Monitoring several distribution points needs manual meter reading at each location.',
      solution: 'Each node measures consumption and transmits data wirelessly to a gateway that displays and logs all points.',
      components: ['Arduino Nano nodes', 'nRF24L01 / LoRa modules', 'Energy sensing modules', 'ESP32 gateway', 'Display'],
      tech: ['RF communication', 'Arduino IDE', 'Web dashboard'],
      functions: ['Readings from multiple nodes', 'Central dashboard view', 'Per-node consumption logs', 'Node offline detection'] },
    { title: 'Automatic Solar Panel Tracking System', branch: 'EEE', tags: ['Automation'], level: 'Beginner', demo: true, icon: 'solar',
      desc: 'A panel that follows the sun for higher energy output than a fixed mount.',
      overview: 'A single or dual-axis solar tracker controlled by light-sensing feedback.',
      problem: 'Fixed solar panels receive direct sunlight only for part of the day, reducing total energy output.',
      solution: 'LDR sensors compare light intensity and a servo or DC motor turns the panel toward the brightest direction.',
      components: ['Arduino', 'LDR sensors', 'Servo / DC geared motor', 'Solar panel', 'Mounting frame'],
      tech: ['Arduino IDE', 'Closed-loop control'],
      functions: ['Automatic sun tracking', 'Output comparison with fixed panel', 'Night-time return to east position', 'Voltage display'] },
    { title: 'Smart Load Management System', branch: 'EEE', tags: ['Automation', 'IoT'], level: 'Intermediate', demo: false, icon: 'load',
      desc: 'Prioritise essential loads and shed non-critical ones during peak demand.',
      overview: 'A demand-side management controller for homes, hostels or small industries.',
      problem: 'Peak demand causes overloads and tripping, cutting power to essential loads along with non-essential ones.',
      solution: 'The controller measures total load and disconnects low-priority loads in order, restoring them when demand drops.',
      components: ['ESP32', 'Current sensors', 'Relay module', 'RTC module', 'LCD'],
      tech: ['Arduino IDE', 'Priority scheduling', 'Mobile app control'],
      functions: ['Priority-based load shedding', 'Time-based scheduling', 'Remote control from phone', 'Load usage display'] },
    { title: 'Battery Monitoring System', branch: 'EEE', tags: ['IoT'], level: 'Intermediate', demo: true, icon: 'battery',
      desc: 'Monitor cell voltage, temperature and charge level of a Li-ion or lead-acid pack.',
      overview: 'A monitoring system for EV and backup battery packs with protection alerts.',
      problem: 'Unmonitored batteries can over-charge, over-discharge or overheat, reducing life and creating safety risks.',
      solution: 'Sensors track each cell and temperature; the controller estimates charge level and warns or cuts off on unsafe conditions.',
      components: ['ESP32', 'Voltage sensing circuit', 'INA219 current sensor', 'NTC thermistors', 'Relay / MOSFET cut-off', 'OLED'],
      tech: ['Arduino IDE', 'State-of-charge estimation', 'IoT dashboard'],
      functions: ['Cell voltage and temperature monitoring', 'Estimated state of charge', 'Over-voltage and under-voltage cut-off', 'Alerts on dashboard'] },
    { title: 'Industrial Motor Monitoring System', branch: 'EEE', tags: ['IoT', 'Automation'], level: 'Advanced', demo: false, icon: 'motor',
      desc: 'Track motor current, temperature and vibration to catch faults early.',
      overview: 'A predictive-maintenance monitor for induction motors used in industries.',
      problem: 'Motors often fail without warning, causing downtime and costly repairs.',
      solution: 'Current, temperature and vibration sensors feed a controller that flags abnormal patterns and can stop the motor.',
      components: ['ESP32', 'ACS712 current sensor', 'DS18B20 temperature sensor', 'ADXL345 vibration sensor', 'Contactor / relay', 'LCD'],
      tech: ['Arduino IDE', 'IoT dashboard', 'Threshold-based fault detection'],
      functions: ['Live current, temperature and vibration', 'Overload and overheat protection', 'Abnormal vibration alert', 'Remote motor stop'] },

    // ===== MECHANICAL =====
    { title: 'Automatic Material Handling System', branch: 'Mechanical', tags: ['Automation'], level: 'Intermediate', demo: false, icon: 'box',
      desc: 'Move and sort materials between stations with minimal manual effort.',
      overview: 'An automated transfer and sorting setup for small manufacturing lines.',
      problem: 'Manual material handling is slow, tiring and error-prone in repetitive production work.',
      solution: 'A motor-driven transfer mechanism with sensors detects objects and routes them to the right station.',
      components: ['DC geared motors', 'IR / colour sensors', 'Arduino', 'Mild steel frame', 'Pusher mechanism'],
      tech: ['Mechanism design', 'Arduino control', 'SolidWorks model'],
      functions: ['Automatic object detection', 'Transfer between stations', 'Basic sorting', 'Emergency stop'] },
    { title: 'Smart Conveyor Belt System', branch: 'Mechanical', tags: ['Automation', 'IoT'], level: 'Intermediate', demo: true, icon: 'conveyor',
      desc: 'A sensor-based conveyor that counts, sorts and reports products.',
      overview: 'A conveyor model with object counting, colour or size sorting and speed control.',
      problem: 'Manual counting and sorting on production lines is slow and inconsistent.',
      solution: 'Sensors on the conveyor detect and classify items, and actuators push them into the correct bins.',
      components: ['Conveyor belt and rollers', 'DC motor with driver', 'IR and colour sensors', 'Servo pushers', 'Arduino / ESP32'],
      tech: ['Arduino IDE', 'Speed control', 'Optional IoT count dashboard'],
      functions: ['Product counting', 'Colour or size-based sorting', 'Adjustable belt speed', 'Production count display'] },
    { title: 'Automatic Hydraulic Press', branch: 'Mechanical', tags: ['Automation'], level: 'Intermediate', demo: false, icon: 'press',
      desc: 'A compact hydraulic press for bending, punching and pressing operations.',
      overview: 'A small-scale automated press using hydraulic force for workshop operations.',
      problem: 'Manual presses need high effort and give inconsistent results for repeated jobs.',
      solution: 'A motor-driven hydraulic pump and cylinder deliver controlled force, with limit switches for automatic cycles.',
      components: ['Hydraulic cylinder', 'Pump and motor', 'Direction control valve', 'Pressure gauge', 'Frame', 'Limit switches'],
      tech: ['Hydraulic circuit design', 'Force calculation', 'CAD modelling'],
      functions: ['Automatic press cycle', 'Controlled pressing force', 'Pressure reading', 'Safety limit switches'] },
    { title: 'Robotic Pick and Place System', branch: 'Mechanical', tags: ['Robotics', 'Automation'], level: 'Advanced', demo: true, icon: 'arm',
      desc: 'A multi-axis robotic arm that picks objects and places them at set positions.',
      overview: 'A servo-driven robotic arm with manual and automatic operating modes.',
      problem: 'Repetitive pick-and-place tasks in industries are tiring for workers and need consistent accuracy.',
      solution: 'A 4-axis arm with a gripper follows recorded or programmed positions to move objects between points.',
      components: ['MG996R servo motors', 'Gripper', 'Arduino', 'Joystick / Bluetooth module', '3D-printed or acrylic links'],
      tech: ['Kinematics', 'Arduino IDE', 'CAD design'],
      functions: ['Manual joystick control', 'Record and replay motion', 'Pick and place at set points', 'Payload testing'] },
    { title: 'Pneumatic Automation System', branch: 'Mechanical', tags: ['Automation'], level: 'Beginner', demo: true, icon: 'pneumatic',
      desc: 'Compressed-air actuators for punching, clamping or lifting tasks.',
      overview: 'A pneumatic automation setup demonstrating industrial actuation with sensors and valves.',
      problem: 'Manual clamping and punching operations are slow and require repeated effort.',
      solution: 'Solenoid valves control double-acting cylinders, triggered by sensors or a timer for automatic operation.',
      components: ['Double-acting cylinder', '5/2 solenoid valve', 'Air compressor', 'FRL unit', 'Sensors', 'Control circuit'],
      tech: ['Pneumatic circuit design', 'Relay / Arduino control'],
      functions: ['Automatic actuation cycle', 'Sensor-triggered operation', 'Adjustable stroke timing', 'Manual override'] },
    { title: 'Smart Vehicle Lifting System', branch: 'Mechanical', tags: ['Automation'], level: 'Intermediate', demo: false, icon: 'lift',
      desc: 'A motorised lift that raises a vehicle safely for servicing.',
      overview: 'A screw or scissor-type lifting mechanism driven by a motor with safety controls.',
      problem: 'Manual jacks take time and effort and can be unsafe during vehicle servicing.',
      solution: 'A motor-driven mechanism raises and lowers the vehicle, with limit switches and remote operation.',
      components: ['DC geared motor', 'Lead screw / scissor linkage', 'Limit switches', 'Remote control', 'Frame'],
      tech: ['Mechanism design', 'Load calculation', 'CAD modelling'],
      functions: ['Motorised lift and lower', 'Upper and lower limit safety', 'Remote operation', 'Load test'] },
    { title: 'Automatic Gear Mechanism', branch: 'Mechanical', tags: ['Automation'], level: 'Beginner', demo: false, icon: 'gear',
      desc: 'Automatic gear shifting based on vehicle speed.',
      overview: 'A model of an automatic gear-changing system for two-wheelers or small vehicles.',
      problem: 'Manual gear shifting is inconvenient in traffic and depends on rider skill.',
      solution: 'A speed sensor feeds a controller that actuates the shift mechanism at set speed thresholds.',
      components: ['Gearbox', 'Speed sensor', 'Actuator (servo / solenoid)', 'Arduino', 'Frame'],
      tech: ['Gear train design', 'Arduino control'],
      functions: ['Speed-based gear shifting', 'Gear position display', 'Manual override', 'Speed-ratio demonstration'] },
    { title: 'Industrial Safety Automation System', branch: 'Mechanical', tags: ['Automation', 'IoT'], level: 'Intermediate', demo: true, icon: 'shield',
      desc: 'Stop machines automatically when a hand enters the danger zone or gas is detected.',
      overview: 'A safety system for press machines and workshops that protects operators.',
      problem: 'Operators get injured when hands enter moving machine areas, and gas or fire hazards go unnoticed.',
      solution: 'IR curtains, gas and flame sensors cut machine power instantly and raise local and remote alerts.',
      components: ['IR sensor array', 'MQ-2 gas sensor', 'Flame sensor', 'Relay / contactor', 'Buzzer', 'ESP32'],
      tech: ['Arduino IDE', 'IoT alerts'],
      functions: ['Instant machine stop on intrusion', 'Gas and fire detection', 'Alarm and remote alert', 'Event log'] },
    { title: 'Solar Tracking Mechanical System', branch: 'Mechanical', tags: ['Automation'], level: 'Beginner', demo: true, icon: 'solar',
      desc: 'A dual-axis tracking structure designed for stability and smooth motion.',
      overview: 'The mechanical design of a dual-axis solar tracker with gear and linkage drive.',
      problem: 'Tracker structures must move smoothly and stay stable under wind while carrying the panel load.',
      solution: 'A dual-axis frame with a gear drive and sensor feedback positions the panel while keeping the structure rigid.',
      components: ['Dual-axis frame', 'Worm gear drive', 'Motors', 'LDR sensors', 'Arduino', 'Solar panel'],
      tech: ['Mechanism design', 'Structural analysis', 'CAD modelling'],
      functions: ['Two-axis sun tracking', 'Stable structure under load', 'Output comparison with fixed mount', 'Smooth gear-driven motion'] },
    { title: 'Mini CNC Automation System', branch: 'Mechanical', tags: ['Automation', 'Robotics'], level: 'Advanced', demo: false, icon: 'cnc',
      desc: 'A compact 2 or 3-axis CNC machine for plotting, engraving or light milling.',
      overview: 'A desktop CNC built with stepper motors, lead screws and open-source firmware.',
      problem: 'Commercial CNC machines are costly for students and small workshops.',
      solution: 'Stepper-driven axes controlled by GRBL firmware follow G-code generated from CAD drawings.',
      components: ['NEMA 17 stepper motors', 'Lead screws and rails', 'Arduino + CNC shield', 'Spindle / laser / pen', 'Frame'],
      tech: ['GRBL firmware', 'G-code', 'CAD / CAM software'],
      functions: ['Multi-axis motion from G-code', 'Plotting or engraving demo', 'Homing and limit switches', 'Accuracy testing'] }
  ];
  PROJECTS.forEach((p, i) => { p.id = i; });

export const DEV_OPTIONS = [
    'Basic working model to demonstrate the core concept',
    'Advanced version with extra features or IoT dashboard',
    'Custom changes to match your guide\'s requirements',
    'Documentation and explanation support — discussed separately'
  ];

  /* ---------- Category data ---------- */
export const EEE_CATS = [
    { name: 'Power Systems', icon: 'bolt', ex: ['Power factor correction', 'Load shedding scheduler', 'Cable fault locator'] },
    { name: 'Renewable Energy', icon: 'solar', ex: ['Solar power monitoring', 'Solar panel tracker', 'Hybrid solar-wind system'] },
    { name: 'Embedded Systems', icon: 'chip', ex: ['Battery monitoring', 'Prepaid energy meter', 'Smart metering unit'] },
    { name: 'IoT', icon: 'wireless', ex: ['Transformer monitoring', 'Smart energy monitor', 'Street light fault reporting'] },
    { name: 'Automation', icon: 'load', ex: ['Smart load management', 'Street light automation', 'Auto changeover switch'] },
    { name: 'Electronics', icon: 'wave', ex: ['Regulated power supply', 'Inverter design', 'Voltage stabiliser'] },
    { name: 'Motor Control', icon: 'motor', ex: ['BLDC speed control', 'Motor condition monitoring', 'Soft starter'] },
    { name: 'Energy Monitoring', icon: 'meter', ex: ['Wireless energy monitor', 'Smart plug', 'Industrial energy meter'] }
  ];
export const CSE_CATS = [{"name": "AI & Machine Learning", "icon": "chip", "ex": ["College FAQ chatbot", "Recommendation system", "Text classification"]}, {"name": "Web Development", "icon": "code", "ex": ["Campus placement portal", "Library management", "Helpdesk ticket management"]}, {"name": "Data Analytics", "icon": "meter", "ex": ["Student performance analytics", "Sales trend dashboard", "Data visualisation"]}, {"name": "Cybersecurity", "icon": "shield", "ex": ["Phishing URL detection", "Password strength analyser", "Log analysis dashboard"]}];
export const MECH_CATS = [
    { name: 'Industrial Automation', icon: 'factory', ex: ['Smart conveyor belt', 'Safety automation', 'Sorting line'] },
    { name: 'Robotics', icon: 'arm', ex: ['Pick and place arm', 'Line follower robot', 'Robotic gripper'] },
    { name: 'Manufacturing', icon: 'cnc', ex: ['Mini CNC machine', 'Sheet metal cutter', 'Drilling fixture'] },
    { name: 'Mechanical Design', icon: 'ruler', ex: ['Automatic gear mechanism', 'Leaf spring design', 'Chassis design'] },
    { name: 'Pneumatics', icon: 'pneumatic', ex: ['Pneumatic punching', 'Pneumatic bumper', 'Pneumatic lifter'] },
    { name: 'Hydraulics', icon: 'drop', ex: ['Hydraulic press', 'Hydraulic jack', 'Scissor lift'] },
    { name: 'CNC', icon: 'gear', ex: ['CNC pen plotter', 'CNC laser engraver', '3-axis router'] },
    { name: 'Material Handling', icon: 'box', ex: ['Automatic material handler', 'Vehicle lifting system', 'Motorised trolley'] }
  ];

export const FAQS = [
    ['Do you have ready-made projects?', 'No. We do not keep projects ready for sale. Your project is started only after you discuss the requirement and confirm the order.'],
    ['What type of project can I request?', 'You can request Diploma, mini and final-year projects in ECE, EEE, CSE, IoT, Mechanical Engineering and web application development.'],
    ['Can I suggest my own project idea?', 'Yes. Students can contact us to discuss their idea and requirements.'],
    ['When will development start?', 'Development starts after the requirements, scope, price, delivery time and order terms are confirmed.'],
    ['Can the project be customized?', 'Yes. Features and components are finalized with you before development begins.'],
    ['Will I receive a demo?', 'You will receive progress updates and a working demonstration of your completed project before final delivery, as agreed in the order scope.'],
    ['How can I contact you?', 'Use WhatsApp at 8142161862 or email imamshas125@gmail.com.'],
    ['How do I order a project?', 'Send your requirement through WhatsApp or the enquiry form. We will discuss it and confirm the scope, price and delivery time before starting.']
  ];

